eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

server:
  port: 8083

spring:
  application:
    name: school
    config:
      students-url: http://localhost:8082/api/v1/students

  config:
    import:
      - optional:configserver:http://localhost:8080

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect



