eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
server:
  port: 8082

spring:
  application:
    name: students

  config:
    import:
      - optional:configserver:http://localhost:8080

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/students
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect


